const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Physics,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.Particles,
		C3.Behaviors.Anchor,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Behaviors.Sin.Exps.Value,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Plugins.Sprite.Acts.RotateCounterclockwise,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Behaviors.Physics.Cnds.IsSleeping,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.Compare
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Physics: 0},
	{GrassTile: 0},
	{SkyTile: 0},
	{Cannon: 0},
	{ScrollTo: 0},
	{ScrollTo2: 0},
	{Cow: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Audio: 0},
	{PowerMeter: 0},
	{Sine: 0},
	{PowerBar: 0},
	{Flag: 0},
	{DistanceText: 0},
	{Smoke: 0},
	{Smoke2: 0},
	{PowerDisplay: 0},
	{PowerArrow: 0},
	{Anchor: 0},
	{HighScore: 0},
	{SineVal: 0},
	{CurrentTurn: 0},
	{Fired: 0}
];

self.InstanceType = {
	GrassTile: class extends self.ITiledBackgroundInstance {},
	SkyTile: class extends self.ITiledBackgroundInstance {},
	Cannon: class extends self.ISpriteInstance {},
	Cow: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	PowerMeter: class extends self.ISpriteInstance {},
	PowerBar: class extends self.ISpriteInstance {},
	Flag: class extends self.ISpriteInstance {},
	DistanceText: class extends self.ITextInstance {},
	Smoke: class extends self.ISpriteInstance {},
	Smoke2: class extends self.IParticlesInstance {},
	PowerDisplay: class extends self.ITextInstance {},
	PowerArrow: class extends self.ISpriteInstance {},
	HighScore: class extends self.ITextInstance {}
}