const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.Car,
		C3.Plugins.TiledBg,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Particles,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Behaviors.Fade,
		C3.Behaviors.Anchor,
		C3.Behaviors.shadowcaster,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.LOS,
		C3.Behaviors.Pin,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Behaviors.Turret,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Behaviors.LOS.Acts.AddObstacle,
		C3.Behaviors.Pathfinding.Acts.AddObstacle,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Car.Cnds.IsMoving,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Behaviors.Pathfinding.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Car.Acts.SetIgnoreInput,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.RotateTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Plugins.Audio.Acts.PlayAtObject,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{Hits: 0},
	{ScrollTo: 0},
	{Car: 0},
	{Player: 0},
	{Player2: 0},
	{TiledBackground: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{Particles: 0},
	{Keyboard: 0},
	{Solid: 0},
	{Sprite: 0},
	{Wall: 0},
	{Particles2: 0},
	{Fade: 0},
	{Treadmarks: 0},
	{Anchor: 0},
	{HealthBar: 0},
	{techframepng: 0},
	{Sprite2: 0},
	{ShadowCaster: 0},
	{Hangar: 0},
	{EnemyHits: 0},
	{Pathfinding: 0},
	{LineOfSight: 0},
	{EnemyTank: 0},
	{EnemyBullet: 0},
	{Pin: 0},
	{Cannon: 0},
	{Mouse: 0},
	{Explosion: 0},
	{Health: 0},
	{HealthSpawn: 0},
	{Score: 0},
	{Audio: 0},
	{Turret: 0},
	{EnemyCannon: 0},
	{Ammo: 0},
	{AmmoCount: 0},
	{GameOver: 0},
	{GameOver2: 0},
	{PressSPACEBARToPlayAgain: 0},
	{PressSPACEBARToPlayAgain2: 0},
	{LifeMarker: 0},
	{Sprite3: 0},
	{TitleGraphic: 0},
	{TitleText: 0},
	{PLAY: 0},
	{HowToPlayText: 0},
	{ButtonBackground: 0},
	{TitleText2: 0},
	{Controls: 0},
	{ControlsText3: 0},
	{ControlsText2: 0},
	{ControlsText1: 0},
	{ControlsText4: 0},
	{Black: 0},
	{InstructionsText4: 0},
	{ControlsText5: 0},
	{ControlsText6: 0},
	{Wall2: 0},
	{FinalScoreText: 0},
	{HealthExists1: 0},
	{AmmoExists: 0},
	{Lives: 0},
	{EnemyFired: 0},
	{Fired: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	Player2: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Bullet: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Wall: class extends self.ISpriteInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Treadmarks: class extends self.ISpriteInstance {},
	HealthBar: class extends self.ISpriteInstance {},
	techframepng: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Hangar: class extends self.ISpriteInstance {},
	EnemyTank: class extends self.ISpriteInstance {},
	EnemyBullet: class extends self.ISpriteInstance {},
	Cannon: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Explosion: class extends self.ISpriteInstance {},
	Health: class extends self.ISpriteInstance {},
	HealthSpawn: class extends self.ISpriteInstance {},
	Score: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	EnemyCannon: class extends self.ISpriteInstance {},
	Ammo: class extends self.ISpriteInstance {},
	AmmoCount: class extends self.ITextInstance {},
	GameOver: class extends self.ITextInstance {},
	GameOver2: class extends self.ITextInstance {},
	PressSPACEBARToPlayAgain: class extends self.ITextInstance {},
	PressSPACEBARToPlayAgain2: class extends self.ITextInstance {},
	LifeMarker: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	TitleGraphic: class extends self.ISpriteInstance {},
	TitleText: class extends self.ITextInstance {},
	PLAY: class extends self.ITextInstance {},
	HowToPlayText: class extends self.ITextInstance {},
	ButtonBackground: class extends self.ITiledBackgroundInstance {},
	TitleText2: class extends self.ITextInstance {},
	Controls: class extends self.ISpriteInstance {},
	ControlsText3: class extends self.ITextInstance {},
	ControlsText2: class extends self.ITextInstance {},
	ControlsText1: class extends self.ITextInstance {},
	ControlsText4: class extends self.ITextInstance {},
	Black: class extends self.ITiledBackgroundInstance {},
	InstructionsText4: class extends self.ITextInstance {},
	ControlsText5: class extends self.ITextInstance {},
	ControlsText6: class extends self.ITextInstance {},
	Wall2: class extends self.ITiledBackgroundInstance {},
	FinalScoreText: class extends self.ITextInstance {}
}