const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Behaviors.Flash,
		C3.Plugins.TiledBg,
		C3.Behaviors.wrap,
		C3.Behaviors.Bullet,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Behaviors.Turret,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Behaviors.solid,
		C3.Behaviors.Rotate,
		C3.Behaviors.Anchor,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.Turret.Acts.SetRateOfFire,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Behaviors.EightDir.Acts.SetDeceleration,
		C3.Behaviors.EightDir.Acts.SetAcceleration,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.OnKey
	];
};
self.C3_JsPropNameTable = [
	{"8Direction": 0},
	{BoundToLayout: 0},
	{Flash: 0},
	{Player: 0},
	{Wrap: 0},
	{SpaceTiles: 0},
	{StarMove: 0},
	{Star: 0},
	{Space: 0},
	{Bullet: 0},
	{Bullet1: 0},
	{Keyboard: 0},
	{Audio: 0},
	{BossHealth: 0},
	{Turret: 0},
	{Sine: 0},
	{Sine2: 0},
	{BossCircle: 0},
	{Particles: 0},
	{RandomFire: 0},
	{MoveDirection: 0},
	{InvaderHealth: 0},
	{Invaders: 0},
	{Solid: 0},
	{LeftBarrier: 0},
	{RightBarrier: 0},
	{Rotate: 0},
	{SquareBullet: 0},
	{PlayerXplode: 0},
	{Anchor: 0},
	{LifeCounter: 0},
	{SquareXplode: 0},
	{ScoreDisplay: 0},
	{LevelDisplay: 0},
	{PowerUpDisplay: 0},
	{BossBullet: 0},
	{BossDam1: 0},
	{PU_Type: 0},
	{PU_Dispenser: 0},
	{StartBkgd: 0},
	{GAMEOVER_Text: 0},
	{TiledBackground: 0},
	{StartScreenText: 0},
	{Logo: 0},
	{Fired: 0},
	{SquareDir: 0},
	{Respawn: 0},
	{Level: 0},
	{Lives: 0},
	{Reshot: 0},
	{Score: 0},
	{SquareInstances: 0},
	{ShotsTaken: 0},
	{ShotsHit: 0},
	{Accuracy: 0},
	{IsBossLevel: 0},
	{PU_Dir: 0},
	{Volume: 0},
	{isLevelingUp: 0},
	{Music: 0},
	{PU: 0},
	{xTraShot: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	SpaceTiles: class extends self.ITiledBackgroundInstance {},
	Star: class extends self.ISpriteInstance {},
	Space: class extends self.ISpriteInstance {},
	Bullet1: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	BossCircle: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Invaders: class extends self.ISpriteInstance {},
	LeftBarrier: class extends self.ISpriteInstance {},
	RightBarrier: class extends self.ISpriteInstance {},
	SquareBullet: class extends self.ISpriteInstance {},
	PlayerXplode: class extends self.IParticlesInstance {},
	LifeCounter: class extends self.ISpriteInstance {},
	SquareXplode: class extends self.IParticlesInstance {},
	ScoreDisplay: class extends self.ITextInstance {},
	LevelDisplay: class extends self.ITextInstance {},
	PowerUpDisplay: class extends self.ITextInstance {},
	BossBullet: class extends self.ISpriteInstance {},
	BossDam1: class extends self.IParticlesInstance {},
	PU_Dispenser: class extends self.ISpriteInstance {},
	StartBkgd: class extends self.ISpriteInstance {},
	GAMEOVER_Text: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	StartScreenText: class extends self.ITextInstance {},
	Logo: class extends self.ISpriteInstance {}
}