const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Plugins.TiledBg,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.Bullet,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Particles,
		C3.Plugins.progressbar,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Behaviors.Pin,
		C3.Behaviors.solid,
		C3.Plugins.Audio,
		C3.Behaviors.LOS,
		C3.Behaviors.custom,
		C3.Behaviors.Follow,
		C3.Behaviors.shadowcaster,
		C3.Plugins.shadowlight,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.SetListenerObject,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.shadowlight.Acts.SetLightColor,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.progressbar.Acts.SetPos,
		C3.Plugins.progressbar.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.shadowlight.Acts.SetLightPosition,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Audio.Acts.PlayAtObjectByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Audio.Acts.PlayAtObject,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.MoveTo.Acts.SetEnabled,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.LOS.Acts.SetRange,
		C3.Behaviors.custom.Acts.PushOutSolid,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.MoveTo.Cnds.IsEnabled,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Behaviors.Pathfinding.Cnds.IsMoving,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Text.Acts.AppendText
	];
};
self.C3_JsPropNameTable = [
	{"8Direction": 0},
	{ScrollTo: 0},
	{Player: 0},
	{DirtGround: 0},
	{ZombieHealth: 0},
	{MoveTo: 0},
	{Pathfinding: 0},
	{Zombie: 0},
	{Bullet: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Particles: 0},
	{ZombieSpawner: 0},
	{PlayerHealthBar: 0},
	{Anchor: 0},
	{AmmoText: 0},
	{Ammunition: 0},
	{MedicKit: 0},
	{Pin: 0},
	{Light1: 0},
	{Solid: 0},
	{Wall: 0},
	{Audio: 0},
	{ZombieCounterText: 0},
	{GameOver: 0},
	{GO_ZombieCounterText: 0},
	{PlayAgainText: 0},
	{GameTitle: 0},
	{StartText: 0},
	{TiledBackground: 0},
	{Barrier: 0},
	{Zombie2: 0},
	{TitleScreen: 0},
	{GameTitle2: 0},
	{isFollowing: 0},
	{isFound: 0},
	{survivortype: 0},
	{LineOfSight: 0},
	{Custom: 0},
	{Survivor: 0},
	{Follow: 0},
	{Survivor2: 0},
	{MedkitsText: 0},
	{Exit: 0},
	{Fence: 0},
	{ShadowCaster: 0},
	{Corner: 0},
	{Black: 0},
	{InstructionsText1: 0},
	{ControlsText1: 0},
	{InstructionsText3: 0},
	{InstructionsText4: 0},
	{Controls: 0},
	{ControlsText2: 0},
	{ControlsText3: 0},
	{ControlsText4: 0},
	{ControlsText5: 0},
	{UncleJimBob: 0},
	{GameOverText1: 0},
	{Car: 0},
	{BulletXplode: 0},
	{Car2: 0},
	{Crate: 0},
	{Dumpster: 0},
	{Tree: 0},
	{Tree2: 0},
	{Shed1: 0},
	{Shed2: 0},
	{SurvivorsFoundText: 0},
	{HeadforExitText: 0},
	{Tower: 0},
	{TowerBorder: 0},
	{ScoringText1: 0},
	{ScoringText2: 0},
	{ScoringText3: 0},
	{Crosshair: 0},
	{SurvivorSpawnPoint: 0},
	{Couch: 0},
	{ShadowLight: 0},
	{Logo: 0},
	{ZombieSpawnTime: 0},
	{PlayerHealth: 0},
	{ZombieCounter: 0},
	{Fired: 0},
	{Ammo: 0},
	{IsFollowing: 0},
	{MedKits: 0},
	{SurvivorsFound: 0},
	{Level: 0},
	{Score: 0},
	{SurvivorBonus: 0},
	{ZombieKillScore: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	DirtGround: class extends self.ITiledBackgroundInstance {},
	Zombie: class extends self.ISpriteInstance {},
	Bullet: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Particles: class extends self.IParticlesInstance {},
	ZombieSpawner: class extends self.ISpriteInstance {},
	PlayerHealthBar: class extends self.IProgressBarInstance {},
	AmmoText: class extends self.ITextInstance {},
	Ammunition: class extends self.ISpriteInstance {},
	MedicKit: class extends self.ISpriteInstance {},
	Light1: class extends self.ISpriteInstance {},
	Wall: class extends self.ITiledBackgroundInstance {},
	Audio: class extends self.IInstance {},
	ZombieCounterText: class extends self.ITextInstance {},
	GameOver: class extends self.ISpriteInstance {},
	GO_ZombieCounterText: class extends self.ITextInstance {},
	PlayAgainText: class extends self.ITextInstance {},
	GameTitle: class extends self.ITextInstance {},
	StartText: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Barrier: class extends self.ISpriteInstance {},
	Zombie2: class extends self.ISpriteInstance {},
	TitleScreen: class extends self.ISpriteInstance {},
	GameTitle2: class extends self.ITextInstance {},
	Survivor: class extends self.ISpriteInstance {},
	Survivor2: class extends self.ISpriteInstance {},
	MedkitsText: class extends self.ITextInstance {},
	Exit: class extends self.ISpriteInstance {},
	Fence: class extends self.ITiledBackgroundInstance {},
	Corner: class extends self.ISpriteInstance {},
	Black: class extends self.ITiledBackgroundInstance {},
	InstructionsText1: class extends self.ITextInstance {},
	ControlsText1: class extends self.ITextInstance {},
	InstructionsText3: class extends self.ITextInstance {},
	InstructionsText4: class extends self.ITextInstance {},
	Controls: class extends self.ISpriteInstance {},
	ControlsText2: class extends self.ITextInstance {},
	ControlsText3: class extends self.ITextInstance {},
	ControlsText4: class extends self.ITextInstance {},
	ControlsText5: class extends self.ITextInstance {},
	UncleJimBob: class extends self.ISpriteInstance {},
	GameOverText1: class extends self.ITextInstance {},
	Car: class extends self.ISpriteInstance {},
	BulletXplode: class extends self.IParticlesInstance {},
	Car2: class extends self.ISpriteInstance {},
	Crate: class extends self.ISpriteInstance {},
	Dumpster: class extends self.ISpriteInstance {},
	Tree: class extends self.ISpriteInstance {},
	Tree2: class extends self.ISpriteInstance {},
	Shed1: class extends self.ISpriteInstance {},
	Shed2: class extends self.ISpriteInstance {},
	SurvivorsFoundText: class extends self.ITextInstance {},
	HeadforExitText: class extends self.ITextInstance {},
	Tower: class extends self.ISpriteInstance {},
	TowerBorder: class extends self.ITiledBackgroundInstance {},
	ScoringText1: class extends self.ITextInstance {},
	ScoringText2: class extends self.ITextInstance {},
	ScoringText3: class extends self.ITextInstance {},
	Crosshair: class extends self.ISpriteInstance {},
	SurvivorSpawnPoint: class extends self.ISpriteInstance {},
	Couch: class extends self.ISpriteInstance {},
	ShadowLight: class extends self.IShadowLightInstance {},
	Logo: class extends self.ISpriteInstance {}
}